# Generated by Django 4.2.20 on 2025-03-25 16:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Article',
            new_name='Crew',
        ),
    ]
