# Generated by Django 4.2.20 on 2025-03-25 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_destination_technologie'),
    ]

    operations = [
        migrations.AddField(
            model_name='crew',
            name='url',
            field=models.URLField(default='http://example.com'),
        ),
        migrations.AddField(
            model_name='destination',
            name='url',
            field=models.URLField(default='http://example.com'),
        ),
        migrations.AddField(
            model_name='technologie',
            name='url',
            field=models.URLField(default='http://example.com'),
        ),
    ]
